/*****************************************************************************
 File:			slider.h
 Description:	The SLIDER control header.
 History:
 Date		| Description										| Name
 -----------+---------------------------------------------------+------
 31/3/94	| Created.											| PW
*****************************************************************************/

/****************************************************************************/
/*								Defines										*/
/****************************************************************************/

#define	IDC_ENV1			100
#define	IDC_A1				101
#define	IDC_A1_VALUE		102
#define	IDC_H1				103
#define	IDC_H1_VALUE		104
#define	IDC_D1				105
#define	IDC_D1_VALUE		106
#define	IDC_S1				107
#define	IDC_S1_VALUE		108
#define	IDC_R1				109
#define	IDC_R1_VALUE		110

#define	IDC_PIN1			120
#define	IDC_PIN1_SLIDER		121

#define	IDC_HIDE1			130
#define	IDC_HIDE2			131
#define	IDC_HIDE3			132
#define	IDC_HIDE4			133
#define	IDC_HIDE5			134
